### ISSUE TITLE
https://nekox.cn

### ISSUE THREAD

**Issue by ghost** [luosiwei-cmd/Friends#4]
\

**Comment by luosiwei-cmd** [comment]
请先添加本站友链

**Comment by luosiwei-cmd** [comment]
添加了说一声哦~

**Comment by luosiwei-cmd** [comment]
哦好的，我看到了

**Comment by luosiwei-cmd** [comment]
已经添加友链，`小伙伴`标签稍后添加~

**Comment by ghost** [comment]
> 已经添加友链，`小伙伴`标签稍后添加~

邮箱md5是`63f77a368c0f83cdbca675c63a9c52bb`啦
谢谢，qwq

**Comment by luosiwei-cmd** [comment]
> > 已经添加友链，`小伙伴`标签稍后添加~
> 
> 邮箱md5是`63f77a368c0f83cdbca675c63a9c52bb`啦
> 谢谢，qwq

已经添加上了呢~

**Comment by luosiwei-cmd** [comment]
这个issue不要close哦，要不然友链就失效了

**Comment by ghost** [comment]
> 这个issue不要close哦，要不然友链就失效了

好的qwq
